# This TOML file encodes what will go into Info.plist.
#
# Update the version below for each release.

CFBundleVersion = "3.3"
CFBundleShortVersionString = "3.3"

# Required fields
CFBundleDisplayName = "SnapPy"
CFBundleExecutable = "SnapPy"
CFBundleIconFile = "SnapPy.icns"
CFBundleIdentifier = "org.example.SnapPy"
CFBundleInfoDictionaryVersion = "6.0"
CFBundleName = "SnapPy"
CFBundlePackageType = "APPL"

# Replace with your copyrignt statement:
NSHumanReadableCopyright = "Copyright (C) 2009 - present Marc Culler, Nathan Dunfield, Matthias Goerner and others"

# Optional fields
CFBundleDevelopmentRegion = "English"
CFBundleSignature = "SnPy"
LSHasLocalizedDisplayName = false
LSRequiresCarbon = true
NSPrincipalClass = "NSApplication"
NSRequiresAquaSystemAppearance = "No"

# AppleScript support
NSAppleScriptEnabled = "YES"
OSAScriptingDefinition = "SnapPy.sdef"

## Each document type supported by this app should have a block below.
[[CFBundleDocumentTypes]]
  CFBundleTypeName = "Python script"
  CFBundleTypeExtensions = [ "py", ]
  CFBundleTypeMIMETypes = [ "application/x-python", ]
  CFBundleTypeOSTypes = [ "TEXT", "****", ]
  CFBundleTypeRole = "Viewer"

[[CFBundleDocumentTypes]]
  CFBundleTypeName = "Link Projection"
  CFBundleTypeExtensions = [ "lnk", ]
  CFBundleTypeMIMETypes = [ "application/text", ]
  CFBundleTypeOSTypes = [ "TEXT", "****", ]
  CFBundleTypeRole = "Viewer"

[[CFBundleDocumentTypes]]
  CFBundleTypeName = "Triangulation"
  CFBundleTypeExtensions = [ "tri", ]
  CFBundleTypeMIMETypes = [ "application/text", ]
  CFBundleTypeOSTypes = [ "TEXT", "****", ]
  CFBundleTypeRole = "Viewer"

[[CFBundleDocumentTypes]]
  CFBundleTypeName = "Surface"
  CFBundleTypeExtensions = [ "sur", ]
  CFBundleTypeMIMETypes = [ "application/text", ]
  CFBundleTypeOSTypes = [ "TEXT", "****", ]
  CFBundleTypeRole = "Viewer"
