# This file is required by BundleUp.
# It provides a TOML description of the same dictionary
# that will be described by the app's Info.plist file.
# Edit appropriately.

# Required fields

CFBundleDisplayName = "SnapPy"
CFBundleExecutable = "SnapPy"
CFBundleIconFile = "SnapPy.icns"
## Replace with your own unique reverse domain: 
CFBundleIdentifier = "org.example.SnapPy"
CFBundleInfoDictionaryVersion = "6.0"
CFBundleName = "SnapPy"
CFBundlePackageType = "APPL"
## Update the version for each release.
CFBundleVersion = "3.3"
CFBundleShortVersionString = "3.3"
## Replace with your copyrignt statement:
NSHumanReadableCopyright = "Copyright (C)" 

# Optional fields
CFBundleDevelopmentRegion = "English"
CFBundleSignature = "????"
LSHasLocalizedDisplayName = false
LSRequiresCarbon = true
NSPrincipalClass = "NSApplication"
NSRequiresAquaSystemAppearance = "No"

# AppleScript support
NSAppleScriptEnabled = "YES"
OSAScriptingDefinition = "SnapPy.sdef"
## Each document type supported by this app should have a block below.
## These are examples.
[[CFBundleDocumentTypes]]
  CFBundleTypeName = "Python script"
  CFBundleTypeExtensions = [ "py", ]
  CFBundleTypeMIMETypes = [ "application/x-python", ]
  CFBundleTypeOSTypes = [ "TEXT", "****", ]
  CFBundleTypeRole = "Viewer"
[[CFBundleDocumentTypes]]
  CFBundleTypeName = "Plain text file"
  CFBundleTypeExtensions = [ "txt", ]
  CFBundleTypeMIMETypes = [ "application/text", ]
  CFBundleTypeOSTypes = [ "TEXT", "****", ]
  CFBundleTypeRole = "Viewer"